#include "StartingoutApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<StartingoutApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

StartingoutApp::StartingoutApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  StartingoutApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  StartingoutApp::associateSyntax(_syntax, _action_factory);
}

StartingoutApp::~StartingoutApp()
{
}

extern "C" void StartingoutApp__registerApps() { StartingoutApp::registerApps(); }
void
StartingoutApp::registerApps()
{
  registerApp(StartingoutApp);
}

void
StartingoutApp::registerObjects(Factory & factory)
{
}

void
StartingoutApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
